josdem/vetlog-spring-boot

src/main/resources/db/migration/V1.4__update_breed.sql

Changing Landrace by Mixed Breed.

#196 Updating breed to mixed breed

---

build.gradle

- Adding Flyway configuration
- Adding Flyway execution rule
**References:**
https://josdem.io/techtalk/spring/spring_boot_flyway/

[small]feature/200

---

build.gradle
src/main/java/com/jos/dem/vetlog/validator/UserValidator.java
src/test/java/com/jos/dem/vetlog/validator/UserValidatorTest.java

HotFix - The last release broke this US: https://github.com/josdem/vetlog-spring-boot/wiki/US3
Jenkins build: https://ci.josdem.io/job/vetlog/21/

[small]feature/221

---

src/main/resources/templates/adoption/descriptionForAdoption.html
src/main/resources/templates/error.html
src/main/resources/templates/home/home.html
src/main/resources/templates/login/login.html
src/main/resources/templates/pet/create.html
src/main/resources/templates/pet/edit.html
src/main/resources/templates/pet/giveForAdoption.html
src/main/resources/templates/pet/list.html
src/main/resources/templates/pet/listForAdoption.html
src/main/resources/templates/petlog/create.html
src/main/resources/templates/petlog/list.html
src/main/resources/templates/recovery/changePassword.html
src/main/resources/templates/recovery/recoveryPassword.html
src/main/resources/templates/service/list.html
src/main/resources/templates/telephone/adopt.html
src/main/resources/templates/user/create.html
src/main/resources/templates/vet/form.html
src/main/resources/templates/vet/list.html

- Using Thymealeaf fragment expressions
- Jenkins job with tests: https://ci.josdem.io/job/vetlog/27/

[small]feature/216

---

build.gradle
src/main/resources/templates/pet/listForAdoption.html

- Adding a carousel element to list pets for adoption view
- Jenkins job: https://ci.josdem.io/job/vetlog/39/

[small]feature/195

---

build.gradle
src/main/java/com/jos/dem/vetlog/controller/PetController.java

- Adding delete method to `PetController`
- Thanks to @marki2121 for doing the delete pet implementation; this one was easy to do :+1: 
- Jenkins job: https://ci.josdem.io/job/vetlog/41/console

[small]feature/192

---

src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/pet/list.html

- Adding a delete button
- Formating sizes depending on buttons on the screen
- Jenkins: https://ci.josdem.io/job/vetlog/43/console

[small]feature/194

---

build.gradle
src/main/java/com/jos/dem/vetlog/config/WebSecurityConfig.java

- Enabling actuator info endpoint
- Enabling actuator health endpoint
- Jenkins: https://ci.josdem.io/job/vetlog/45/

[small]feature/215

---

build.gradle
src/main/resources/templates/fragments/include.html

- Adding Varela and Monserrat fonts with `https` protocol
- Jenkins: https://ci.josdem.io/job/vetlog/47/

[tiny]feature/219

---

src/main/java/com/jos/dem/vetlog/config/WebSecurityConfig.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/login/login.html

I have used .**failureUrl("/login?error=true")** in the WebSecurityConfig file to use Spring Security Feature that will enable error detection and redirect it to login page with error as true value.
In the login page I have added the Thymeleaf error detection feature to display if password or username dont match.

Fixed Issue : Invalid credentials message is not shown #232

---

src/main/java/com/jos/dem/vetlog/controller/RecoveryController.java
src/main/resources/templates/login/login.html
src/main/resources/templates/recovery/changePassword.html
src/main/resources/templates/recovery/recoveryPassword.html

- Adding a message to the user when trying to change the password
- Adding a message to the user when the password is changed
@SinyukKirill please accept my invite so I can send you code reviews.

[small]feature/235

---

build.gradle
src/main/resources/templates/pet/list.html
src/main/resources/templates/pet/listForAdoption.html

- Adding Thymeleaf expressions to carousel buttons
- Updating to release version 🎉

[small]feature/236

---

.github/workflows/main.yml
src/main/resources/application.yml

- Adding Github actions
- Adding basic application YAML configuration
- Setting up MySQL using Flyway
- Running tests

[small]feature/280

---

.github/workflows/main.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

- Updating to the latest versions

[small]feature/283

---

src/main/java/com/josdem/vetlog/service/impl/RecoveryServiceImpl.java
src/test/java/com/josdem/vetlog/service/RecoveryServiceTest.java

- Validating a token is present
- Adding test with negative scenario

[small]feature/289

---

build.gradle
src/main/java/com/josdem/vetlog/command/AdoptionCommand.java
src/main/java/com/josdem/vetlog/command/ChangePasswordCommand.java
src/main/java/com/josdem/vetlog/command/PetCommand.java
src/main/java/com/josdem/vetlog/command/PetLogCommand.java
src/main/java/com/josdem/vetlog/command/RecoveryPasswordCommand.java
src/main/java/com/josdem/vetlog/command/TelephoneCommand.java
src/main/java/com/josdem/vetlog/command/UserCommand.java
src/main/java/com/josdem/vetlog/command/UsernameCommand.java
src/main/java/com/josdem/vetlog/controller/AdoptionController.java
src/main/java/com/josdem/vetlog/controller/PetController.java
src/main/java/com/josdem/vetlog/controller/PetLogController.java
src/main/java/com/josdem/vetlog/controller/RecoveryController.java
src/main/java/com/josdem/vetlog/controller/TelephoneController.java
src/main/java/com/josdem/vetlog/controller/UserController.java
src/main/java/com/josdem/vetlog/controller/VetController.java
src/main/resources/application.yml
src/test/java/com/josdem/vetlog/controller/UserControllerTest.java

- Adding `jakarta.validation` API
- Adding user's registration test
- Updating command and controllers with valid annotations

[medium]feature/296

---

build.gradle
src/main/java/com/josdem/vetlog/command/AdoptionCommand.java
src/main/java/com/josdem/vetlog/controller/AdoptionController.java
src/main/java/com/josdem/vetlog/validator/AdoptionValidator.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/test/java/com/josdem/vetlog/validator/AdoptionCommandValidatorTest.java
src/test/java/com/josdem/vetlog/validator/AdoptionValidatorTest.java

- Adding adoption validator
- Adding test

[small]feature/293

---

build.gradle
src/main/resources/application.yml
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/pet/listForAdoption.html

[small]feature/282

---

.github/workflows/main.yml
build.gradle

[small]feature/291

---

build.gradle
src/main/java/com/josdem/vetlog/binder/PetBinder.java
src/main/java/com/josdem/vetlog/exception/HandlerException.java
src/main/java/com/josdem/vetlog/service/impl/PetImageServiceImpl.java
src/test/java/com/josdem/vetlog/controller/PetControllerTest.java

- Adding test to register a pet
- Adding test to change pet status from `IN_ADOPTION` to `OWNED`

[small]feature/284

---

build.gradle
src/main/java/com/josdem/vetlog/enums/PetStatus.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/pet/edit.html

- Adding pet status dropdown menu
- Showing dropdown only admin users
- Updating to release version 🎉

[small]feature/285

---

src/main/java/com/josdem/vetlog/enums/VaccinationStatus.java
src/main/java/com/josdem/vetlog/model/Vaccination.java

Creating a model file containing fields
```
name (Vaccination name)
date (MM/dd/YYYY format)
status (PENDING, APPLIED)
```

[small]feature/304

---

src/main/resources/db/migration/V1.5__update_breed.sql

Replaced "Landrace" in the pull-down data that appears when selecting a cat with 'Mixed Breed'

[small]feature/309

---

build.gradle

update gladle
- Flyway MySQL is updated to 10.17.3
- Spring Boot to 3.3.3

[small]feature/317

---

src/main/resources/templates/vet/list.html

Hi @josdem Please review it and let me know if any changes required!

carousel fixed for pet list for admin

---

src/main/resources/templates/user/create.html

- Incorporating drop-down menu from branch: https://github.com/josdem/vetlog-spring-boot/pull/322
- Merging changes.
**Screenshots**

[small]Adding changes suggested by @AviraLS22

---

src/main/java/com/josdem/vetlog/model/Vaccination.java
src/main/java/com/josdem/vetlog/repository/VaccinationRepository.java
src/main/java/com/josdem/vetlog/service/VaccinationService.java
src/main/java/com/josdem/vetlog/service/impl/PetServiceImpl.java
src/main/java/com/josdem/vetlog/service/impl/VaccinationServiceImpl.java
src/main/resources/db/migration/V1.8__adding_pet_vaccination.sql
src/test/java/com/josdem/vetlog/service/PetServiceTest.java
src/test/java/com/josdem/vetlog/service/VaccinationServiceTest.java

- Adding vaccination repository
- Adding vaccination service
- Adding logic to schedule vaccinations based on how old it is the dog, following this program: https://github.com/josdem/vetlog-spring-boot/wiki/Vaccination-Program
- Adding required tests to cover functionality

[small]feature/305

---

src/main/java/com/josdem/vetlog/controller/AdoptionController.java
src/main/java/com/josdem/vetlog/controller/BreedController.java
src/main/java/com/josdem/vetlog/controller/PetLogController.java
src/main/java/com/josdem/vetlog/controller/TelephoneController.java

- Replaced all instances of string concatenation in log.info statements with string formatting placeholders in all the controllers.

Refactor logging statements to eliminate string concatenation

---

build.gradle

Acceptance Criteria
- Flyway MySQL is updated to 10.18.0
- Spring cloud gcp dependencies to 5.6.1
- Mockito-Inline to 5.2.0
- Spring Boot to 3.3.4
- All test are passing
all tests passed and boot run , 
Confirmed startup

Update dependencies to the latest version

---

build.gradle
src/main/java/com/josdem/vetlog/controller/AdoptionController.java
src/main/java/com/josdem/vetlog/service/impl/PetPrescriptionServiceImpl.java
src/main/java/com/josdem/vetlog/service/impl/PetServiceImpl.java
src/main/resources/templates/adoption/descriptionForAdoption.html
src/main/resources/templates/telephone/adopt.html
src/test/java/com/josdem/vetlog/controller/AdoptionControllerTest.java
src/test/java/com/josdem/vetlog/controller/PetControllerTest.java
src/test/java/com/josdem/vetlog/controller/PetLogControllerTest.java
src/test/java/com/josdem/vetlog/controller/TelephoneControllerTest.java
src/test/java/com/josdem/vetlog/service/PetServiceTest.java
src/test/java/com/josdem/vetlog/service/UserServiceTest.java

- Adding controller test cases
- Coverage increased to 83%
**Screenshot**

[small]feature/360

---

src/main/java/com/josdem/vetlog/advice/AfterThrowingAdvice.java
src/main/java/com/josdem/vetlog/command/PetLogCommand.java
src/main/java/com/josdem/vetlog/config/VaccinationStrategyConfig.java
src/main/java/com/josdem/vetlog/config/WebSecurityConfig.java
src/main/java/com/josdem/vetlog/controller/BreedController.java
src/main/java/com/josdem/vetlog/exception/HandlerWrapper.java
src/main/java/com/josdem/vetlog/helper/LocaleResolver.java
src/main/java/com/josdem/vetlog/model/User.java
src/main/java/com/josdem/vetlog/service/impl/LocaleServiceImpl.java
src/main/java/com/josdem/vetlog/service/impl/RecoveryServiceImpl.java
src/test/java/com/josdem/vetlog/controller/PetControllerTest.java
src/test/java/com/josdem/vetlog/helper/LocaleResolverTest.java
src/test/java/com/josdem/vetlog/service/LocaleServiceTest.java
src/test/java/com/josdem/vetlog/service/PetLogServiceTest.java
src/test/java/com/josdem/vetlog/service/RecoveryServiceTest.java
src/test/java/com/josdem/vetlog/service/UserDetailsServiceTest.java
src/test/java/com/josdem/vetlog/service/VaccinationServiceTest.java
src/test/java/com/josdem/vetlog/util/DateFormatterTest.java
src/test/java/com/josdem/vetlog/validator/UserValidatorTest.java

- Solving Sonarcloud issues
**References**
https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&id=josdem_vetlog-spring-boot

[medium]Feature/364

---

src/main/java/com/josdem/vetlog/controller/AdoptionController.java
src/main/java/com/josdem/vetlog/controller/LoginController.java
src/main/java/com/josdem/vetlog/controller/PetController.java
src/main/java/com/josdem/vetlog/controller/PetLogController.java
src/main/java/com/josdem/vetlog/controller/RecoveryController.java
src/main/java/com/josdem/vetlog/controller/TelephoneController.java
src/main/java/com/josdem/vetlog/controller/UserController.java
src/main/java/com/josdem/vetlog/controller/VetController.java

- Introducing var in controllers

[small]Feature/346

---

src/main/resources/templates/pet/giveForAdoption.html
src/test/java/com/josdem/vetlog/util/DateFormatterTest.java

- Fixing tests when user locale is set to Spanish

[small]Feature/361

---

src/main/resources/templates/adoption/descriptionForAdoption.html
src/main/resources/templates/pet/giveForAdoption.html

- Fixing birthdate format in give for adoption view
- Fixing birthdate format in description for adoption view
**Screenshots**

[small]Feature/345

---

build.gradle
src/main/java/com/josdem/vetlog/binder/PetBinder.java
src/main/java/com/josdem/vetlog/command/PetCommand.java
src/main/java/com/josdem/vetlog/controller/PetController.java
src/main/java/com/josdem/vetlog/enums/VaccinationStatus.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/pet/edit.html
src/test/java/com/josdem/vetlog/binder/PetBinderTest.java
src/test/java/com/josdem/vetlog/controller/PetControllerTest.java
src/test/java/com/josdem/vetlog/enums/VaccinationStatusTest.java

- Setting vaccines as select / option fields
- Updating vaccination status date
- Adding vaccination list field to the tests
- Setting up release version 🎉
**Screenshot**

[medium]Feature/344

---

build.gradle

- `org.flywaydb.flyway` updated to `10.19.0`
- `spring-cloud-gcp-dependencies` updated to `5.7.0`
- `json-smart` updated to `2.4.9`

[small]Feature/381

---

build.gradle
src/main/resources/templates/pet/list.html

- Improving vaccines style
**Screenshot**

[small]Feature/378

---

src/main/java/com/josdem/vetlog/controller/VetController.java
src/main/resources/templates/vet/list.html

On the search page with administrator privileges
AS IS
No vaccination records are shown
TOBE
View the list of vaccines

[small]Feature/376

---

build.gradle
src/main/java/com/josdem/vetlog/binder/PetBinder.java
src/test/java/com/josdem/vetlog/binder/PetBinderTest.java

- Showing only vaccines in "Pending" status on pet's edit view
**Screenshots**

[small]Feature/390

---

build.gradle
src/main/java/com/josdem/vetlog/controller/PetController.java
src/main/java/com/josdem/vetlog/repository/VaccinationRepository.java
src/main/java/com/josdem/vetlog/service/VaccinationService.java
src/main/java/com/josdem/vetlog/service/impl/PetServiceImpl.java
src/main/java/com/josdem/vetlog/service/impl/VaccinationServiceImpl.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/pet/list.html
src/test/java/com/josdem/vetlog/service/PetServiceTest.java
src/test/java/com/josdem/vetlog/service/VaccinationServiceTest.java

- Creating a modal for each pet in the list to fix the bug
- Deleting all pet vaccines in order to delete a pet
**References**
- Bug solution was found [here](https://stackoverflow.com/questions/64878101/how-to-pass-object-to-modal-dialog-in-thymeleaf)

[small]Feature/392

---

build.gradle
src/main/resources/templates/login/login.html

- Adding `test-id` values to the UI components

[small]Feature/403

---

build.gradle
src/main/resources/templates/login/login.html
src/main/resources/templates/user/create.html

- Adding `test-id` values to the UI components

[small]feature/402

---

src/main/resources/templates/pet/edit.html

Adding test-id locators to the pet edit view

---

src/main/resources/templates/pet/list.html

#408 
Hello, I am a university student and I am trying to complete a project for my open source projects course, where I need to contribute to an active open source repository. I would like to submit a pull request and receive feedback on it if possible. This is my first contribution to any project, so I might be a bit off track.

Adding test-id locators to the pet list view

---

build.gradle
src/main/resources/templates/vet/form.html

- Adding `test-id` values to username and submit buttons

[small]feature/404

---

build.gradle
src/main/resources/templates/vet/list.html

- Adding `test-id` locator values

[small]feature/406

---

build.gradle
src/main/resources/templates/vet/list.html

[small]Hot fix/changing id to dewormed

---

src/main/resources/templates/vet/list.html

@josdem  I added the button and used same modal as in pet/list.html. I also made some changes so the design looks the same as in user pet list. If there is anything that is not to your liking, just let me know and I'll fix it right up.

Add delete pet functionality to the admin user #433

---

build.gradle
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties

- Deleting unused i18n messages

[small]Feature/432

---

src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/test/java/com/josdem/vetlog/controller/PetControllerTest.java

- Avoiding duplicate code
- Adding missing message

[small]hotFix/avoiding-duplicate-code-adding-missing-message

---

build.gradle

- Updating dependencies to the latest versions

[small]Feature/427

---

build.gradle
src/main/resources/templates/error.html
src/main/resources/templates/home/home.html
src/main/resources/templates/petlog/create.html
src/main/resources/templates/recovery/recoveryPassword.html

[small]Feature/431

---

src/main/java/com/josdem/vetlog/command/PetCommand.java
src/main/java/com/josdem/vetlog/validator/PetValidator.java
src/main/resources/i18n/messages.properties
src/main/resources/templates/pet/create.html
src/main/resources/templates/pet/edit.html

Regarding Ticket [#445](https://github.com/josdem/vetlog-spring-boot/issues/445)
This issue is also happening to me in Chrome and Safari.
My proposed solution is to separate the forms from birthDateTime to birthDate and birthTIme, which would be combined when the date is being validated

Added Separate Field In Form To Add Optional Birth Time (Issue #445)

---

build.gradle
src/main/java/com/josdem/vetlog/client/GoogleStorageWriter.java
src/main/java/com/josdem/vetlog/controller/RecoveryController.java
src/main/java/com/josdem/vetlog/controller/TelephoneController.java
src/main/java/com/josdem/vetlog/helper/StorageOptionsHelper.java
src/main/java/com/josdem/vetlog/util/UuidGenerator.java
src/main/resources/templates/telephone/adopt.html
src/test/java/com/josdem/vetlog/client/GoogleStorageWriterTest.java
src/test/java/com/josdem/vetlog/controller/LoginControllerTest.java
src/test/java/com/josdem/vetlog/controller/PetControllerTest.java
src/test/java/com/josdem/vetlog/controller/RecoveryControllerTest.java
src/test/java/com/josdem/vetlog/controller/TelephoneControllerTest.java

- Increase code coverage
- Deleting some unused methods

[small]Feature/430

---

build.gradle
src/main/resources/application.yml
src/main/resources/static/assets/servizi-dog-theme/package.json

- Updating Bootstrap to the latest compatible version
- Updating JQuery to the latest version
- Updating Font-awesome to the latest version
- Setting release version 🎉

[small]Feature/444

---

build.gradle
src/main/java/com/josdem/vetlog/strategy/vaccination/impl/DogVaccinationStrategy.java
src/test/java/com/josdem/vetlog/service/VaccinationServiceTest.java
src/test/java/com/josdem/vetlog/strategy/DogVaccinationStrategyTest.java

- Moving dog vaccination four weeks

[small]Feature/465

---

build.gradle
src/main/java/com/josdem/vetlog/strategy/vaccination/impl/CatVaccinationStrategy.java
src/test/java/com/josdem/vetlog/strategy/CatVaccinationStrategyTest.java

- Updating vaccination schedule

[small]Feature/464

---

build.gradle
src/main/java/com/josdem/vetlog/service/impl/RecoveryServiceImpl.java
src/main/resources/application.yml
src/test/java/com/josdem/vetlog/service/RecoveryServiceTest.java

- Removing unused properties values
**Note:** We decided not moving forward with a template properties class since adds unnecessary complexity to the code.

[small]Feature/456

---

build.gradle.kts
src/main/java/com/josdem/vetlog/service/impl/RecoveryServiceImpl.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/error.html

- Adding missing user not found messages
- Adding some style to the error message
- Updarting version

[small]Feature/462

---

src/main/resources/i18n/messages_es.properties

I got your message and changed accordingly, although I didn't change the "src/main/resources/templates/fragments/footer.html" 
since I didn't understand what you were trying to say earlier.

Corrected incorrect label in contact us

---

src/main/resources/db/migration/V1.9__adding_breeds.sql

Added the following breeds and a few others as well :
- Australian Cattle
- Miniature Pinscher
- Goldendoodle
- Schnoodle
Created a new migration file called "V1.9__adding_breeds.sql" at "vetlog-spring-boot\src\main\resources\db\V1.9__adding_breeds.sql".

Added a few missing dog breeds

---

build.gradle.kts

i have updated the build.gradle.kts file to the requested versions:
Spring Boot is updated to 3.4.2
Flyway Gradle Plugin is updated to 11.3.1
Kotlin JVM is updated to 2.1.10
Spring Cloud GCP is updated to 6.0.0
Jetbrains Annotations is updated to 26.0.2
Json Smart is updated to 2.5.1
Cglib Nodep is updated to 3.3.0
Mockito Kotlin is updated to 5.4.0

updated dependencies

---

build.gradle.kts
src/main/java/com/josdem/vetlog/controller/BreedController.java
src/main/java/com/josdem/vetlog/controller/PetController.java

I have added the sort logic for all types of pets including dogs and cats.
I have made this branch from my previous change: update-dependencies/486
for consistency, however if you would like me to create completely serperate branches 
for each issue in the future, please let me know!
I tried to match your branch naming convention, but if there is a preferred format for 
issue contribution please let me know as well so I could follow it from now on. 
Thank you!

/pet/create breed sort logic

---

build.gradle.kts
src/main/java/com/josdem/vetlog/model/User.java
src/main/java/com/josdem/vetlog/repository/UserRepository.java
src/main/java/com/josdem/vetlog/validator/UserValidator.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/test/java/com/josdem/vetlog/validator/UserValidatorTest.java

- Adding find by country code and mobile to the user repository
- Adding logic to the user validator
- Adding test

[small]feature/508

---

build.gradle.kts
src/main/java/com/josdem/vetlog/strategy/vaccination/impl/DogVaccinationStrategy.java
src/main/java/com/josdem/vetlog/util/VaccineFormatter.java
src/test/java/com/josdem/vetlog/util/VaccineFormatterTest.java

- Adding Canine Influenza text formmater when user locale is in Spanish
- Adding test

[small]Feature/510

---

build.gradle.kts
src/test/java/com/josdem/vetlog/service/AdoptionServiceTest.kt
src/test/java/com/josdem/vetlog/service/BreedServiceTest.kt
src/test/java/com/josdem/vetlog/service/EmailServiceTest.kt
src/test/java/com/josdem/vetlog/service/LocaleServiceTest.kt
src/test/java/com/josdem/vetlog/service/PetImageServiceTest.kt
src/test/java/com/josdem/vetlog/service/PetLogServiceTest.kt
src/test/java/com/josdem/vetlog/service/PetPrescriptionServiceTest.kt
src/test/java/com/josdem/vetlog/service/PetServiceTest.kt
src/test/java/com/josdem/vetlog/service/RecoveryServiceTest.kt
src/test/java/com/josdem/vetlog/service/RegistrationServiceTest.kt
src/test/java/com/josdem/vetlog/service/RestServiceTest.kt
src/test/java/com/josdem/vetlog/service/TelephoneServiceTest.kt
src/test/java/com/josdem/vetlog/service/UserDetailsServiceTest.kt
src/test/java/com/josdem/vetlog/service/UserServiceTest.kt
src/test/java/com/josdem/vetlog/service/VaccinationServiceTest.kt

- Adding `testInfo` to the test method and use it to log the test name

[small]Feature/488

---

build.gradle.kts
src/main/java/com/josdem/vetlog/config/ApplicationProperties.java
src/main/java/com/josdem/vetlog/controller/PetLogController.java
src/main/resources/application.yml
src/main/resources/templates/petlog/create.html
src/test/java/com/josdem/vetlog/controller/PetLogControllerTest.java

- Adding veterinarians to the application properties Yaml file
- Adding veterinarians to the pet log controller
- Adding veterianrians to the pet log view
- Adding veterinarians to the test

[small]Feature/524

---

build.gradle.kts
src/main/java/com/josdem/vetlog/binder/PetLogBinder.java
src/main/java/com/josdem/vetlog/command/PetLogCommand.java
src/main/java/com/josdem/vetlog/model/PetLog.java
src/main/java/com/josdem/vetlog/service/impl/PetLogServiceImpl.java
src/main/java/com/josdem/vetlog/service/impl/PetPrescriptionServiceImpl.java
src/main/resources/db/migration/V1.10__adding_attachment.sql
src/main/resources/templates/petlog/list.html
src/test/java/com/josdem/vetlog/binder/PetLogBinderTest.kt
src/test/java/com/josdem/vetlog/service/PetPrescriptionServiceTest.kt

- Adding has attachment field to the pet log model
- Setting has attachment to true when we upload any prescription to the Google bucket
- Showing attachment link only if we have an attachment
- Updating tests

[small]Feature/517

---

src/test/java/com/josdem/vetlog/enums/PetStatusTest.kt
src/test/java/com/josdem/vetlog/enums/VaccinationStatusTest.kt

Translated java files to kotlin.
Runned tests, everything passed successfully.
#530

Move from Java to Kotlin in enums test #530

---

src/main/resources/i18n/messages_es.properties
src/test/java/com/josdem/vetlog/client/GoogleStorageWriterTest.kt
src/test/java/com/josdem/vetlog/enums/PetStatusTest.kt
src/test/java/com/josdem/vetlog/enums/VaccinationStatusTest.kt

- Replacing `println` sentences by `log.info`
- Removing unnecessary `@DisplayName` annotation
- Introducing backtick in test methods
- Formatting code

[small]hotFix/improving-some-tests

---

src/test/java/com/josdem/vetlog/binder/PetBinderTest.kt
src/test/java/com/josdem/vetlog/controller/PetControllerTest.kt
src/test/java/com/josdem/vetlog/controller/RecoveryControllerTest.kt
src/test/java/com/josdem/vetlog/enums/VaccinationStatusTest.kt
src/test/java/com/josdem/vetlog/validator/AdoptionValidatorTest.java

Fix #543: Use unique UUIDs across test cases

---

build.gradle.kts

Updates all dependencies to meet current standards while maintaining compatibility as requested on #531. Includes:
- Spring Boot 3.4.4
- Kotlin JVM 2.1.20
- Flyway MySQL 11.4.0 (temporary fallback due to flyway/flyway#4053)
- Spring Cloud GCP 6.1.1
- Json Smart 2.5.2
- Mockito Core 5.16.1
- SonarQube Gradle Plugin 6.1.0.5360
✅ All tests passing  
✅ Build completes successfully  
✅ Manual verification of core functionality

chore: update dependencies to latest stable versions

---

build.gradle.kts
src/main/java/com/josdem/vetlog/binder/PetLogBinder.java
src/main/java/com/josdem/vetlog/controller/PetLogController.java
src/main/java/com/josdem/vetlog/repository/PetLogRepository.java
src/main/java/com/josdem/vetlog/service/PetLogService.java
src/main/java/com/josdem/vetlog/service/impl/PetLogServiceImpl.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/petlog/edit.html
src/main/resources/templates/petlog/list.html
src/test/java/com/josdem/vetlog/binder/PetLogBinderTest.kt
src/test/java/com/josdem/vetlog/controller/PetLogControllerTest.kt
src/test/java/com/josdem/vetlog/service/PetLogServiceTest.kt

- Adding petlog edit functionality
- Adding petlog edit tests
- Showing edit button only if admin user

[medium]Feature/253

---

build.gradle.kts
src/main/java/com/josdem/vetlog/binder/PetLogBinder.java
src/main/java/com/josdem/vetlog/command/PetLogCommand.java
src/main/java/com/josdem/vetlog/service/impl/PetLogServiceImpl.java
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/petlog/edit.html
src/test/java/com/josdem/vetlog/binder/PetLogBinderTest.kt
src/test/java/com/josdem/vetlog/service/PetLogServiceTest.kt

- Adding attribute id to the `PetLogCommand`
- Moving code to the binder
- Updating tests
- Setting release version 🎉

[small]hotFix/avoiding-duplicate-pet-logs

---

src/main/java/com/josdem/vetlog/controller/PetController.java

- fixed sorting while editing pets

fix: sorting while editing pets

---

build.gradle.kts
src/main/java/com/josdem/vetlog/command/MobileCommand.java
src/main/java/com/josdem/vetlog/config/ClientConfiguration.java
src/main/java/com/josdem/vetlog/config/GmailerProperties.java
src/main/java/com/josdem/vetlog/config/GoogleProperties.java
src/main/java/com/josdem/vetlog/model/GoogleResponse.java
src/main/java/com/josdem/vetlog/model/Location.java
src/main/java/com/josdem/vetlog/model/MobileCommand.java
src/main/java/com/josdem/vetlog/service/GoogleService.java
src/main/java/com/josdem/vetlog/service/impl/GoogleServiceImpl.java
src/main/resources/application.yml
src/test/java/com/josdem/vetlog/service/GoogleServiceTest.kt

- Adding Google Geolocation API request
- Adding Retrofit Client
- Adding Google Geolocation test

[medium]Feature/553

---

build.gradle.kts
src/main/java/com/josdem/vetlog/cache/ApplicationCache.java
src/main/java/com/josdem/vetlog/command/PetGeolocation.java
src/main/java/com/josdem/vetlog/config/GeolocationProperties.java
src/main/java/com/josdem/vetlog/config/WebSecurityConfig.java
src/main/java/com/josdem/vetlog/controller/GoogleMapController.java
src/main/java/com/josdem/vetlog/controller/LocationController.java
src/main/java/com/josdem/vetlog/model/Location.java
src/main/resources/application.yml
src/main/resources/templates/map/map.html
src/test/java/com/josdem/vetlog/controller/GoogleMapControllerTest.kt
src/test/java/com/josdem/vetlog/controller/LocationControllerTest.kt

- Adding geolocation end-point to store a pet location
- Getting pet's location from a `HashMap`
- Setting default location

[medium]Feature/577

---

build.gradle.kts
src/main/java/com/josdem/vetlog/cache/ApplicationCache.java
src/main/java/com/josdem/vetlog/command/PetGeolocation.java
src/main/java/com/josdem/vetlog/controller/GoogleMapController.java
src/main/java/com/josdem/vetlog/controller/LocationController.java
src/main/resources/i18n/messages.properties
src/main/resources/i18n/messages_es.properties
src/main/resources/templates/map/map.html
src/test/java/com/josdem/vetlog/controller/GoogleMapControllerTest.kt

- Adding header when a pet is geolocated
- Adding header when w pet is not geolcated

[small]Feature/579

---

src/main/resources/db/migration/V1.11__remove_breed.sql

[#590] : Bull Terrier appears duplicated in dogs breed list
Expected Result
No duplicated breeds on the list.

[#590] : Bull Terrier appears duplicated in dogs breed list

---

build.gradle.kts
src/main/java/com/josdem/vetlog/controller/LocationController.java
src/main/java/com/josdem/vetlog/model/Location.java
src/test/java/com/josdem/vetlog/controller/LocationControllerTest.kt

- Update location to all pets in the cache 
- Add required tests
- Update version

[small]Feature/593

---

src/main/java/com/josdem/vetlog/controller/PetLogController.java
src/main/java/com/josdem/vetlog/model/PetLog.java
src/main/java/com/josdem/vetlog/service/PetLogService.java
src/main/java/com/josdem/vetlog/service/impl/PetLogServiceImpl.java
src/main/resources/db/migration/V1.12__adding_username_column_in_pet_log.sql
src/test/java/com/josdem/vetlog/service/PetLogServiceTest.kt

- Added Flyway migration to include username column
- Updated PetLog save flow to capture current user's username
- Updated unit tests to assert username persistence

feat(petlog): add username to pet_log table and save logic

---

build.gradle.kts
src/main/java/com/josdem/vetlog/command/PetLogCommand.java
src/main/java/com/josdem/vetlog/service/impl/PetLogServiceImpl.java
src/test/java/com/josdem/vetlog/service/PetLogServiceTest.kt

- Getting username from the database when user edits a pet log

[small]getting-username-from-the-database-when-updating-pet-log

---

build.gradle.kts

- Bumping up dependency versions
- Setting release version 🎉

[small]Feature/588

---

build.gradle.kts
src/main/java/com/josdem/vetlog/controller/LocationController.java
src/main/resources/application.yml
src/test/java/com/josdem/vetlog/controller/LocationControllerTest.kt

- Adding a user token to the store pet's location request
- Adding required tests

[small]Feature/621

---

build.gradle.kts
src/main/resources/application.yml

Updated the said dependencies to the latest version and all tests are passing
this is in reference to issue https://github.com/josdem/vetlog-spring-boot/issues/615

Updated dependencies to latest version

---

build.gradle.kts
src/main/java/com/josdem/vetlog/strategy/vaccination/impl/DogVaccinationStrategy.java
src/main/java/com/josdem/vetlog/util/VaccineFormatter.java
src/test/java/com/josdem/vetlog/util/VaccineFormatterTest.kt

- Changing Canine Influenza by Bordetella
- Updating tests

[small]Feature/619

---

build.gradle.kts
docker/.dockerignore
docker/DOCKER_SETUP.md
docker/Dockerfile
docker/docker-compose.yml

Closes #638 
This PR introduces Docker and Docker Composesupport to simplify local development and streamline onboarding. It eliminates the need for manual setup of the application and database by providing containerized environments.
---
- **Dockerfile**:
- Multi-stage build with:
- `gradle:8.8-jdk21` for building the app
- `eclipse-temurin:21-jre` for lightweight production image
- Includes healthcheck, code formatting (Spotless), and non-root user for security
- **.dockerignore**: Created to exclude unnecessary files from Docker builds.
- **docker-compose.yml**:
- Added multi-service setup with:
- `mysql` container using `mysql:8.0`
- `vetlog-app` Spring Boot app container built via custom `Dockerfile`
- Shared network and healthchecks
- **env.example**: Provided example environment …

Feature/638 Added Dockerfile and docker-compose

---

build.gradle.kts
src/main/resources/templates/petlog/edit.html

- Adding missing uuid parameter

[small]Feature/651

---

src/main/resources/templates/adoption/descriptionForAdoption.html
src/main/resources/templates/pet/edit.html
src/main/resources/templates/telephone/adopt.html
src/main/resources/templates/vet/form.html

Implements #670. I have also implemented the fix across all the pages that face the same issue. Please let me know if you have any suggestions/fixes. Thank you for this opportunity.

Fix Spanish Labels

---

CONTRIBUTING.md
README.md

Fixes #635
This pull request enhances the contribution experience for the Vetlog Spring Boot project by adding a detailed contributing guide and updating the README to encourage contributions. The most important changes are summarized below.

docs: add contributing guide and link in README

---

src/main/resources/db/migration/V1.17__adding_breeds.sql

@josdem 
Could you please review this?  
I want to gradually contribute more to this project, so I will make sure to check in regularly :)
Issue: #678

Added Calupoh dog breed to migrations

---

build.gradle.kts
src/main/java/com/josdem/vetlog/controller/PetController.java

- Fixing bug, list is not populated when we want to create a new pet

[small]Feature/705

---

build.gradle.kts
src/main/java/com/josdem/vetlog/strategy/vaccination/impl/DogVaccinationStrategy.java
src/test/java/com/josdem/vetlog/strategy/DogVaccinationStrategyTest.kt

- Adding deworming process between week 0 and 5
- Adding test scenario
- Updating project version

[small]Feature/728
